<a href="https://colab.research.google.com/github/PosgradoMNA/actividades-de-aprendizaje-aleislasb/blob/main/Semana%203%20IBM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#5.1-Numpy 1D Arrays



In [37]:
#Numpy is a library for scientific computing and it is the base of pandas, a numpy array is similar to a list.
import pandas as np
a=np.array([1,-7,5,-9])


In [9]:
#We can also consult which data do we have on which position like in the first videos.
a[0]

1

In [11]:
#We can also the consult the type of information we are typing. 
type(a)

pandas.core.arrays.integer.IntegerArray

In [12]:
#In order to consult the size of the numpy we can use the function .size.
a.size

2

In [39]:
#As in some features we can add more elements to our list or tuple. Or slice the same tuple, for example the first two elements of the list. 
b=a[0:2]
b

<IntegerArray>
[1, -7]
Length: 2, dtype: Int64

In [44]:
#We can also perform basic operations, in this case addition or multiply vectors. 
#The addition is made: Nominators with nominators and denominators with denominators.
#If we perform the numpy library is faster than other methodology.
import numpy as np

u=np.array([1,1])
v=np.array([0,1])

z=u+v
z

array([1, 2])

In [47]:
#There are some basic functions that also numpy can perform, such as mean or max.
import numpy as np 
a=np.array([1,-1,1,-1])
mean_a=a.mean()
mean_a

1

In [48]:
max_a=a.max()
max_a

1

In [54]:
#With this formula we are adding the values corresponding to the positions that every list have on the different arrays.
import numpy as np
arr1 = np.array([10, 11, 12, 13, 14, 15])
arr2 = np.array([20, 21, 22, 23, 24, 25])
arr3=np.add(arr1,arr2)
arr3

array([30, 32, 34, 36, 38, 40])

In [57]:
#With this formula we are doing a substraction from the first array to the second according to their position.
import numpy as np
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])
arr3=np.subtract(arr1,arr2)
arr3

array([-10,  -1,   8,  17,  26,  35])

In [58]:
#Here as the last iterations, we are multiplying each value according to their position.
import numpy as np
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([2, 1, 2, 3, 4, 5])
arr3=np.multiply(arr1,arr2)
arr3

array([ 20,  20,  60, 120, 200, 300])

In [59]:
#We can multiply a vector with an integer, the integer multiplies every value on the tuple.
z = np.array([2, 4])
-2*z

array([-4, -8])

#5.2-Numpy 2D Arrays

In [68]:
#Numpy can also create 2D arrays, like matrixes on math. On which every subgroup is a new row on the array. 
a=[[11,12,13],[21,22,23],[31,32,33]]
A=np.array(a)
A

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [70]:
#In this case we can ask for the number of lists, in this case the first one is the one that shows first dimension and the second one the shape of the same list.
A.ndim

2

In [71]:
#The formula .shape represents the number of the nested list that we have in all our variable, this can be on a horizontal list or in a rectangular form. 
A.shape

(3, 3)

In [ ]:
#The method 